version: "1.0"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      ALIVE_NAME: $ALIVE_NAME
      BOT_TOKEN: $BOT_TOKEN
      BOT_NAME: $BOT_NAME
      ASSISTANT_NAME: $ASSISTANT_NAME
      SUDO_USERS: $SUDO_USERS
      SESSION_NAME: $SESSION_NAME
      DURATION_LIMIT: $DURATION_LIMIT
      GROUP_SUPPORT: $GROUP_SUPPORT
      UPDATES_CHANNEL: $UPDATES_CHANNEL
      BOT_USERNAME: $BOT_USERNAME
      OWNER_USERNAME: $OWNER_USERNAME
      OWNER_ID: $OWNER_ID
      OWNER_NAME: $OWNER_NAME
      HEROKU_APP_NAME: $HEROKU_APP_NAME
      HEROKU_API_KEY: $HEROKU_API_KEY
      START_PIC: $START_PIC
      ALIVE_IMG: $ALIVE_IMG
      COMMAND_PREFIXES: $COMMAND_PREFIXES
      UPSTREAM_REPO: $UPSTREAM_REPO
      IMG_1: $IMG_1
      IMG_2: $IMG_2
      IMG_3: $IMG_3
      IMG_4: $IMG_4
      IMG_5: $IMG_5
      IMG_6: $IMG_6
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: '1AZWarzQBuxNHR_5VyZB_B71tOYfa-I95-RWlLWpSXFTbSq1tJ5UlAx-oW6iwhoZzYLPBoNngpFRB7PKEqJxOGKduV_vPCuUoIwnAqpplKqBL7NeE-YYmN-xDGXyJ1UoAyxgctPHlR_Uvjl3xrZQTV9fYhi_zTBMDJDe6WxZiKXiigDFjrjl89LA0yXqISDudhTmaeiyqFFDJf7A_FIN3lqsEKsS2itpGg6tHjRPunE0zcPC9mkZanMFQYUGbxWVA7cGcfJd_XTSHjlme-3mBRddRer4TYoaFeWDLA_lfAJObJ64R4WRDGAeT13sAAaTdfzMmyYNzwiAu1orcqLH6WYBcb_x8_GM=' 

workflows:
  example-workflow:
    jobs:
      - example-job
